<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \AHT\QA\Block\Form $block */
?>
<?= $block->getChildHtml('list.qa')?>
<h1><?= $block->getCurrentProduct()->getName() ?></h1>
<div class="block review-add">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Write Your Own Review')) ?></strong></div>
<div class="block-content">
<?php if ($block->getCustomerSession()->isLoggedIn()) : ?>
<form action="<?= $block->escapeUrl('qanda/product/save') ?>" class="qa-form" method="post" id="qa-form" data-role="product-qa-form" data-bind="scope: 'qa-form'" data-mage-init='{"validation":{}}'>
    <?= $block->getBlockHtml('formkey') ?>
    <?= $block->getChildHtml('form_fields_before') ?>
    <input type="text" name="productid" value="<?= $block->getCurrentProduct()->getId()?>" hidden/>
    <fieldset class="fieldset qa-fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field qa-field-question required">
            <label for="question_field" class="label"><span><?= $block->escapeHtml(__('Your Question')) ?></span></label>
            <div class="control">
                <textarea name="question" id="question_field" cols="5" rows="3" data-validate="{required:true}" data-bind="value: qa().detail"></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar review-form-actions">
        <div class="primary actions-primary">
            <button name="createbtn" type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Submit Your Question')) ?></span></button>
        </div>
    </div>
</form>
<?php else : ?>
    <div class="message info notlogged" id="review-form">
        <div>
            <?= $block->escapeHtml(__('Only registered users can write questions. Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()), ['a']) ?>
        </div>
    </div>
<?php endif ?>
</div>
</div>
